project_id = "md-paste"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://su27.github.io/mdpaste/"
additional_redirect_urls = [
  "http://localhost:5173",
  "https://su27.github.io/mdpaste/",
]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600

[storage]
enabled = true

[functions.paste]
verify_jwt = false

[functions.upload-image]
verify_jwt = false

[functions.app]
verify_jwt = false
